version: '3'

services:
  db:
    image: mongo:5.0
    restart: always
    ports:
      - "${DB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    container_name: ${CONTAINER_NAME:-mongodb}
    volumes:
      - ./mongodata:/data/db
